In [280]:
import numpy as np

In [281]:
import random

In [282]:
class Network(object):
    def __init__(self,sizes) -> None:
        self.NumberOfLayers= len(sizes)
        self.biases= [np.random.randn(y,1) for y in sizes[1:]]
        self.weights=[np.random.randn(y,x) for x,y in zip(sizes[:-1],sizes[1:])]
    def sigmoid(self,z):
        return 1.0/(1.0 + np.exp(-z)) 
    def DSigmoid(self,z):
        return self.sigmoid(z) * (1-self.sigmoid(z))     
    def FeedForward(self,a):
        for b,w in zip(self.biases,self.weights):
           a = self.sigmoid(np.dot(w,a) + b)
        return a 
    def CostDerivative(self,OutputActivations,y):
       return (OutputActivations - y)

    def BackProp(self,x,y):
        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w= [np.zeros(w.shape) for w in self.weights]
        
        activation = x
        # List to store all the activations , layer by layer
       
        activations = [x]
        # List to store all the z, layer by layer
        zs = []
        activations.append(activation)
        # Compute zl as in step 2
        for b,w in zip(self.biases,self.weights):
            z = np.dot(w,activation) + b
            zs.append(z)
            activation = self.DSigmoid(z)
            activations.append(activation)
        # Compute the output error deltaL 
        delta = self.CostDerivative(activations[-1],y) * self.DSigmoid(zs[-1])
        nabla_b[-1] = delta
        nabla_w[-1] = np.dot(delta,activations[-2].transpose())

        # Backpropogate the error as in step 4
        for l in range(2,self.NumberOfLayers):
            z = (zs[-l])
            sp = self.DSigmoid(z)

            delta = np.dot(self.weights[-l + 1].transpose(),delta ) * sp
            nabla_b[-l] = delta
            nabla_w[-l] = np.dot(delta,activations[-l-1].transpose())   

        print("Actual output ={0}, Label= {1}" .format(activations[-1],y)) 
        return (nabla_b,nabla_w)

    def UpdateMiniBatch(self,miniBatch,eta):
        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]
        
        for x,y in miniBatch:
            delta_nabla_b ,delta_nabla_w = self.BackProp(x,y)
            nabla_b=[nb +dnb for nb,dnb in zip(nabla_b,delta_nabla_b)]
            nabla_w=[nw + dnw  for nw,dnw in zip(nabla_w,delta_nabla_w)]
            
            self.weights = [w - (eta/len(miniBatch)) * nw for w,nw in zip(self.biases,nabla_b)]
            self.biases =  [b - (eta/len(miniBatch)) * nb for b,nb in zip(self.biases,nabla_b)]
         
    def Evaluate(self,testData):
        return       
    def SGD(self,TrainingData,epochs,minibatch_size, eta,TestData=None):
        if TestData:
            nTest = len(TestData)
        n = len(TrainingData)
        for j in range(epochs):
            random.shuffle(TrainingData)
            miniBatches = [TrainingData[k:k + minibatch_size] for k in range(0,n,minibatch_size)]
            for miniBatch in miniBatches:
                self.UpdateMiniBatch(miniBatch,eta)
            if TestData:
                 print("Epoch{0}:{1} / {2}".format(j,self.Evaluate(TestData),nTest))
            else:
                 print("Epoch{0} complete".format(j))

                


In [283]:
network =Network([2,3,1])

In [284]:
a1 = [1,2]

In [285]:
a1 =np.reshape(a1,(2,1))

In [286]:
activations = network.FeedForward(a1)

In [287]:
activations

array([[0.06387801]])

In [288]:
nabla_b=[np.zeros(b.shape) for b in network.weights]

In [289]:
nabla_b

[array([[0., 0.],
        [0., 0.],
        [0., 0.]]), array([[0., 0., 0.]])]

In [290]:
network.weights[0].shape

(3, 2)

In [291]:
network.weights[1].shape

(1, 3)

In [292]:
print(network.weights[1])

[[-0.20088436  1.59622473 -1.60096264]]


In [293]:
print(network.biases[1])

[[-1.77845448]]


In [294]:
delta_nabla_w=[np.ones(b.shape) for  b in nabla_b]

In [295]:
nabla_w=[nw + dnw for nw,dnw in zip(nabla_b,delta_nabla_w)]

In [296]:
for nw,dnw in zip(nabla_b,delta_nabla_w):
    print(nw)
    print(dnw)
    print(nw + dnw)


[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 0.]]
[[1. 1. 1.]]
[[1. 1. 1.]]


In [297]:
p=np.array([[3],[4]])

In [298]:
p

array([[3],
       [4]])

In [299]:
q=np.array([[2],[5]])

In [300]:
s = p.T

In [301]:
e=p*q

In [302]:
e

array([[ 6],
       [20]])

In [303]:
e.shape

(2, 1)

In [304]:
from sklearn import datasets

In [305]:
feature_sets,labels=datasets.make_moons(100,noise=0.10)

In [306]:
feature_sets.shape

(100, 2)

In [307]:
feature_sets[5,:]

array([-0.79096651,  0.6128386 ])

In [311]:
training_data = feature_sets[0:75]

In [309]:
test_data = feature_sets[76:89]

In [310]:
network.SGD(training_data,30,10,3.0)

Actual output =[[0.12074917 0.11991125]], Label= 1.04170406914347


ValueError: shapes (1,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)